
[data]
train    = ['mega-v3-0.snappy', 'stockfish-d1-0.snappy', 'stockfish-d3-0.snappy']
validate = ['mega-v3-1.snappy', 'stockfish-d1-1.snappy', 'stockfish-d3-1.snappy']
test     = ['mega-v3-2.snappy', 'stockfish-d1-2.snappy', 'stockfish-d3-21.snappy']

shuffle = 10240
batch = 1024
prefetch = 8

[model]
l2 = 0.0
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 128
num_resnet_cnn = 16
do_flatten1x1 = true

bn_momentum = 0.99

[train]
optimizer = 'Adam'
epochs = 10

steps_per_epoch = 10
validation_steps = 10
test_steps = 100

lr_schedule = 'warm_linear'
lr = 0.01
warmup = 5
lr_max_decay_factor = 0.5
