
[data]
train    = ['stockfish-v5-d3-9.recordio']
validate = ['stockfish-v5-d3-8.recordio']
test     = ['stockfish-v5-d3-7.recordio']

shuffle = 1024
batch = 16
prefetch = 1

[model]
l2 = 0.0
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 4
num_cnn = 4

bn_momentum = 0.99
do_flatten1x1 = true

[train]
optimizer = 'Adam'
epochs = 10

steps_per_epoch = 9
validation_steps = 8
test_steps = 7

lr_schedule = 'cosine'
lr = 0.01
first_decay_steps = 10 # compare w/ epochs
alpha = 0.10
