
[data]
train    = ['stockfish-d1-0.snappy',
 	    'stockfish-d1-1.snappy',
 	    'stockfish-d1-2.snappy',
 	    'stockfish-d1-3.snappy',
 	    'stockfish-d1-4.snappy',
 	    'stockfish-d1-5.snappy',
 	    'stockfish-d1-6.snappy',
 	    'stockfish-d1-7.snappy']	 
validate = 'stockfish-d1-8.snappy'
test     = 'stockfish-d1-9.snappy'

shuffle = 1024
batch = 1024
prefetch = 2

[model]
l2 = 0.0
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 32
num_resnet_cnn = 4
do_flatten1x1 = true

bn_momentum = 0.99

[train]
optimizer = 'Adam'
epochs = 10

steps_per_epoch = 10
validation_steps = 1
test_steps = 1

lr_schedule = 'warm_linear'
lr = 0.01
warmup = 5
lr_max_decay_factor = 0.5

