
[data]
train    = ['stockfish-d3-0.recordio',
 	    'stockfish-d3-1.recordio',
 	    'stockfish-d3-2.recordio',
 	    'stockfish-d3-3.recordio',
 	    'stockfish-d3-4.recordio',
 	    'stockfish-d3-5.recordio',
 	    'stockfish-d3-6.recordio',
 	    'stockfish-d3-7.recordio']	 
validate = 'stockfish-d3-8.recordio'
test     = 'stockfish-d3-9.recordio'

shuffle = 20480
batch = 1024
prefetch = 2

[model]
l2 = 0.0
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 32
num_resnet_cnn = 4
do_flatten1x1 = true

bn_momentum = 0.99

[train]
optimizer = 'Adam'
epochs = 300

steps_per_epoch = 100
validation_steps = 25
test_steps = 1000

lr_schedule = 'warm_linear'
lr = 0.01
warmup = 5
lr_max_decay_factor = 0.5

