
[data]
train    = 'mega-v2-0.snappy'
validate = 'mega-v2-1.snappy'
test     = 'mega-v2-2.snappy'

shuffle = 10240
batch = 1024
prefetch = 4


[model]
l2 = 0.0
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 64
num_cnn = 4

bn_momentum = 0.99

[train]
optimizer = 'Adam'
epochs = 100

steps_per_epoch = 50
validation_steps = 25
test_steps = 128

lr_schedule = 'cosine'
lr = 0.01
first_decay_steps = 10 # compare w/ epochs
alpha = 0.10
