
[data]
train    = 'mega-v2-0.leveldb'
validate = 'mega-v2-1.leveldb'
test     = 'mega-v2-2.leveldb'

shuffle = 1024
batch = 128
prefetch = 2


[model]
l2 = 1e-5
activation = 'relu'
dropout = 0.0

top_tower = [1024]

num_filters = 64
num_cnn = 3

bn_momentum = 0.99

[train]
epochs = 2
steps_per_epoch = 25
validation_steps = 10
test_steps = 100

lr = 0.01
first_decay_steps = 5 # compare w/ epochs
alpha = 0.10
