[data]

batch = 1024

train     = ['data/f100.rio-0000[0-8]-of-00010']
validate  = ['data/f100.rio-00009-of-00010']

[model]

type = 'bias_only'

[train]

epochs = 25
steps_per_epoch = 25
val_steps = 10

lr = 0.01
warmup = 5
