[data]

batch = 1024

train     = ['data/f1000.rio-000[1-9]?-of-00100']
validate  = ['data/f1000.rio-000[0-0]?-of-00100']

[model]

type = 'cnn'
l2 = 1e-6
num_filters = 16
num_layers = 4
top_tower = [ 256 ]
kernel = 'random_uniform'
activation = 'sigmoid'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 25

lr = 0.01
warmup = 10
