[data]

batch = 1024

files     = ['data/f1000.rio-000??-of-00100']

[model]

type = 'cnn'
l2 = 1e-6
num_filters = 16
num_layers = 4
top_tower = [ 256 ]
kernel = 'random_uniform'
activation = 'elu'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 10

lr = 0.01
lr_max_decay_factor = 0.90
warmup = 10

[tune]

trials = 100
executions = 2
log_dir = '/tmp/tune_out4'
tb_dir  = '/tmp/tune_logs4'

activations = ['elu']
