[data]

batch = 1024

files     = ['data/f1000.rio-000??-of-00100']

[model]

type = 'cnn'
l2 = 1e-6
num_filters = 16
num_layers = 4
top_tower = [ 256 ]
kernel = 'random_normal'
activation = 'elu'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 50

lr = 0.005
lr_max_decay_factor = 0.10

adam_beta_1 = 0.60
adam_beta_2 = 0.995
adam_epsilon = 1e-10
adam_amsgrad = false

[tune]

trials = 100
executions = 1
log_dir = '/tmp/tune_lr_16_log'
tb_dir  = '/tmp/tune_lr_16_tb'

num_filters_list = [32, 48, 64, 96, 112, 128, 144, 160, 192]
num_layers_list =  [4, 5, 6, 7, 8, 9, 10, 12]
top_tower_list = [ 128, 256, 512, 768, 1024, 1280, 1536 ]
tune_do_flatten_1x1 = true
