[data]

batch = 1024

files     = ['data/f1000.rio-000??-of-00100']

[model]

type = 'cnn'
l2 = 1e-6
num_filters = 192
num_layers = 7
top_tower = [ 512 ]

kernel = 'random_normal'
activation = 'elu'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 50

lr = 0.005
lr_max_decay_factor = 0.10

adam_beta_1 = 0.60
adam_beta_2 = 0.995
adam_epsilon = 1e-10
adam_amsgrad = false

max_gradient = 0.0

[tune]

trials = 50
executions = 2
log_dir = '/tmp/tune_lr_19_log'
tb_dir  = '/tmp/tune_lr_19_tb'

l2_list = [1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-9, 1e-10]
max_gradients = [10.0, 1.0, 0.1, 0.0]
