[data]

batch = 1024

files     = ['data/f1000.rio-000??-of-00100']

[model]

type = 'cnn'
l2 = 1e-6
num_filters = 16
num_layers = 4
top_tower = [ 256 ]
kernel = 'random_uniform'
activation = 'elu'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 25

lr = 1.0
lr_max_decay_factor = 0.10

[tune]

trials = 100
executions = 1
log_dir = '/tmp/tune_lr_9_log'
tb_dir  = '/tmp/tune_lr_9_tb'

activations = ['elu']
lrs = [1e-1, 5e-2, 1e-2, 5e-3, 1e-3, 5e-4, 1e-4]
lr_max_decay_factors = [0.90, 0.75, 0.50, 0.25, 0.10]
