[data]

batch = 1024

train     = ['data/f1000.rio-000[0-9]?-of-00100']
validate  = ['data/f1000.rio-0009?-of-00100']

[model]

type = 'simple'
num_layers = 0
l2 = 1e-6
activation = 'elu'

[train]

epochs = 1900
steps_per_epoch = 100
val_steps = 10

lr = 0.001
warmup = 10
