[data]

batch = 1024

files     = ['data3/twic1092.rio', 'data3/twic1093.rio']

[model]

type = 'transformer'

embedding_dim = 64
intermediate_dim = 128
num_heads = 4
num_layers = 4

l2 = 1e-9
dropout = 0.05

kernel = 'random_normal'
activation = 'gelu'

[train]

epochs = 100
steps_per_epoch = 25
val_steps = 10

lr = 0.0005
lr_max_decay_factor = 0.10

adam_beta_1 = 0.60
adam_beta_2 = 0.995
adam_epsilon = 1e-10
adam_amsgrad = false

max_gradient = 1.0
