[data]

batch = 1024

train     = ['data/f10.rio-0000[0-8]-of-00010']
validate  = ['data/f10.rio-00009-of-00010']

[model]

activation = 'elu'
num_filters = 0
num_layers = 0


[train]

epochs = 1000
steps_per_epoch = 10
val_steps = 100

lr = 0.01
warmup = 10
