[data]

batch = 1024

train     = ['data/f10.rio-0000[0-8]-of-00010']
validate  = ['data/f10.rio-00009-of-00010']

[model]

activation = 'elu'
num_filters = 0
num_layers = 0

[train]

epochs = 1000
steps_per_epoch = 100
val_steps = 50

lr = 0.1
warmup = 10
